name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flatpak Builder
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: fr.daemonwhite.Inspira.devel.json
          manifest-path: flatpak/fr.daemonwhite.Inspira.devel.json

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: mingw-w64-ucrt-x86_64-gtk4 mingw-w64-ucrt-x86_64-libadwaita mingw-w64-ucrt-x86_64-python-pip mingw-w64-ucrt-x86_64-python-gobject mingw-w64-ucrt-x86_64-python-yaml mingw-w64-ucrt-x86_64-python-requests mingw-w64-ucrt-x86_64-python-pillow mingw-w64-ucrt-x86_64-desktop-file-utils mingw-w64-ucrt-x86_64-ca-certificates mingw-w64-ucrt-x86_64-meson git # mingw-w64-ucrt-x86_64-blueprint-compiler

      - name: Setup Blueprint
        shell: msys2 {0}
        run: |
          git clone https://gitlab.gnome.org/GNOME/blueprint-compiler.git
          cd blueprint-compiler
          git checkout v0.18.0
          meson setup builddir
          meson compile -C builddir
          meson install -C builddir

      - name: Compile
        shell: msys2 {0}
        run: |
          meson setup _build
          ninja -C _build install
          pacman --noconfirm -Rs mingw-w64-ucrt-x86_64-desktop-file-utils mingw-w64-ucrt-x86_64-meson git

      - name: Test
        shell: msys2 {0}
        run: |
          set +e
          timeout 2 inspira; [ "$?" -eq "124" ]

      - name: Inno Setup
        run: iscc ".\_build\build-aux\windows\Inspira.iss"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Installer
          path: _build/build-aux/windows/Output/Inspira Windows.exe
